### ISSUE TITLE
Installing “seti-monokai@0.3.1” failed.

### ISSUE THREAD

**Issue by HenderOrlando** [schmittyjd/monokai-seti#16] opened 2015-06-20 21:23 UTC
Unable to download https://www.atom.io/api/packages/seti-monokai/versions/0.3.1/tarball: 400 Bad Request Repository inaccessible

**Comment by schmittyjd** [comment] 2015-06-22 19:32
Ah, had to change the link to the git repo in the package.json (I recently changed my github username) try installing it now and let me know if it still fails. Thanks for submitting the issue. Totally would not have caught this!

**Comment by Kamilius** [comment] 2015-09-26 17:32
@schmittyjd I just got the same issue

**Comment by schmittyjd** [comment] 2015-09-29 16:50
@Kamilius can you confirm that this is still happening? I cannot reproduce on my end. Was able to uninstall/reinstall today

**Comment by Kamilius** [comment] 2015-09-30 17:25
@schmittyjd yes, tried it one more time. Giving you an Atom console screenshot:

![screenshot from 2015-09-30 19 22 12](https://cloud.githubusercontent.com/assets/3115794/10200844/f9ad8e14-67a8-11e5-8be5-cca4b5edc566.png)

**Comment by straku** [comment] 2015-11-09 11:32
@schmittyjd Since yesterday I'm getting the same error. Any help?

**Comment by schmittyjd** [comment] 2015-11-09 21:37
As I am unable to reproduce this error I am driven to believe that this has to be an inconsistency in atoms package distribution

**Comment by schmittyjd** [comment] 2015-11-10 01:57
if anything as a last resort with this theme you can just clone it locally, and then from inside the repo on your machine run ```apm link``` and you would be good to go.

**Comment by brunoduran** [comment] 2015-11-18 18:07
I am having exactly the same problem. Using `apm link` works, however

**Comment by toddsor** [comment] 2015-12-21 14:49
I am getting this same error today: 

```
Installing “seti-monokai@0.3.1” failed.
Unable to download https://www.atom.io/api/packages/seti-monokai/versions/0.3.1/tarball: 400 Bad Request Repository inaccessible
```

**Comment by schmittyjd** [comment] 2015-12-21 18:04
@toddsor there are a few things I need to change, should resolve this problem for everyone by the end of the day

**Comment by atkinchris** [comment] 2017-03-09 10:23
I'm closing this issue as it's been resolved for over a year, and the package is available to download without `400` errors. If there are new errors from `apm` please raise them separately.

**Closed by atkinchris** 2017-03-09 10:23 UTC
